In [111]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/adhilmuhammed/Library/Python/3.12/lib/python/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/adhilmuhammed/Library/Python/3.12/lib/python/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/adhilmuhammed/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/adhilmuhammed/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [112]:
import pandas as pd

In [113]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [114]:
# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [117]:
df.head() # First 5 rows
df.tail() # Last 5 rows
df.info() # Info about DataFrame
df.describe() # Summary statistics

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [118]:
# Column selection
df['Name']
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [119]:
# Row selection by label and position

df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [120]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [121]:
df['Gender'] = ['F','M'] # Add new column

In [122]:
df.isnull()
df.dropna()
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [123]:
df.groupby('Gender')['Age'].mean()
# df.drop('Age', axis=1, inplace=True)

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [124]:
df1 = pd.DataFrame({
    'key': [1, 2],
    'Name': ['Alice', 'Bob']
})

df2 = pd.DataFrame({
    'key': [1, 2],
    'Age': [25, 30]
})

pd.merge(df1, df2, on='key')

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [125]:
df1 = pd.DataFrame({'Name':['Alice','Bob']})
df2 = pd.DataFrame({'Age':[25,30]})

df1.join(df2)

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
# Read CSV
# df = pd.read_csv('output.csv')

In [126]:
# Write CSV
df.to_csv('output.csv', index=False)

In [127]:
print(df.columns)

Index(['Name', 'Age', 'Gender'], dtype='str')

In [128]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64